session_name: "doris"
windows:
  - layout: b23d,193x41,0,0,0
    options: {}
    panes:
      - focus: "true"
        shell_command: htop
    start_directory: /home/jacko
    window_name: htop
  - focus: "true"
    layout: b23f,193x41,0,0,2
    options:
      "@tmux_window_name_enabled": 1
    panes:
      - pane
    start_directory: /home/jacko/projects/doris.nvim
    window_name: doris.nvim
